import {
  amber,
  amberA,
  blackA,
  blue,
  blueA,
  green,
  greenA,
  slate,
  slateA,
  tomato,
  tomatoA,
  whiteA,
} from '@radix-ui/colors'

export const globalTheme = {
  colors: {
    ...whiteA,
    ...blackA,

    primary1: blue.blue1,
    primary2: blue.blue2,
    primary3: blue.blue3,
    primary4: blue.blue4,
    primary5: blue.blue5,
    primary6: blue.blue6,
    primary7: blue.blue7,
    primary8: blue.blue8,
    primary9: blue.blue9,
    primary10: blue.blue10,
    primary11: blue.blue11,
    primary12: blue.blue12,
    primaryA1: blueA.blueA1,
    primaryA2: blueA.blueA2,
    primaryA3: blueA.blueA3,
    primaryA4: blueA.blueA4,
    primaryA5: blueA.blueA5,
    primaryA6: blueA.blueA6,
    primaryA7: blueA.blueA7,
    primaryA8: blueA.blueA8,
    primaryA9: blueA.blueA9,
    primaryA10: blueA.blueA10,
    primaryA11: blueA.blueA11,
    primaryA12: blueA.blueA12,

    neutral1: slate.slate1,
    neutral2: slate.slate2,
    neutral3: slate.slate3,
    neutral4: slate.slate4,
    neutral5: slate.slate5,
    neutral6: slate.slate6,
    neutral7: slate.slate7,
    neutral8: slate.slate8,
    neutral9: slate.slate9,
    neutral10: slate.slate10,
    neutral11: slate.slate11,
    neutral12: slate.slate12,
    neutralA1: slateA.slateA1,
    neutralA2: slateA.slateA2,
    neutralA3: slateA.slateA3,
    neutralA4: slateA.slateA4,
    neutralA5: slateA.slateA5,
    neutralA6: slateA.slateA6,
    neutralA7: slateA.slateA7,
    neutralA8: slateA.slateA8,
    neutralA9: slateA.slateA9,
    neutralA10: slateA.slateA10,
    neutralA11: slateA.slateA11,
    neutralA12: slateA.slateA12,

    success1: green.green1,
    success2: green.green2,
    success3: green.green3,
    success4: green.green4,
    success5: green.green5,
    success6: green.green6,
    success7: green.green7,
    success8: green.green8,
    success9: green.green9,
    success10: green.green10,
    success11: green.green11,
    success12: green.green12,
    successA1: greenA.greenA1,
    successA2: greenA.greenA2,
    successA3: greenA.greenA3,
    successA4: greenA.greenA4,
    successA5: greenA.greenA5,
    successA6: greenA.greenA6,
    successA7: greenA.greenA7,
    successA8: greenA.greenA8,
    successA9: greenA.greenA9,
    successA10: greenA.greenA10,
    successA11: greenA.greenA11,
    successA12: greenA.greenA12,

    error1: tomato.tomato1,
    error2: tomato.tomato2,
    error3: tomato.tomato3,
    error4: tomato.tomato4,
    error5: tomato.tomato5,
    error6: tomato.tomato6,
    error7: tomato.tomato7,
    error8: tomato.tomato8,
    error9: tomato.tomato9,
    error10: tomato.tomato10,
    error11: tomato.tomato11,
    error12: tomato.tomato12,
    errorA1: tomatoA.tomatoA1,
    errorA2: tomatoA.tomatoA2,
    errorA3: tomatoA.tomatoA3,
    errorA4: tomatoA.tomatoA4,
    errorA5: tomatoA.tomatoA5,
    errorA6: tomatoA.tomatoA6,
    errorA7: tomatoA.tomatoA7,
    errorA8: tomatoA.tomatoA8,
    errorA9: tomatoA.tomatoA9,
    errorA10: tomatoA.tomatoA10,
    errorA11: tomatoA.tomatoA11,
    errorA12: tomatoA.tomatoA12,

    warning1: amber.amber1,
    warning2: amber.amber2,
    warning3: amber.amber3,
    warning4: amber.amber4,
    warning5: amber.amber5,
    warning6: amber.amber6,
    warning7: amber.amber7,
    warning8: amber.amber8,
    warning9: amber.amber9,
    warning10: amber.amber10,
    warning11: amber.amber11,
    warning12: amber.amber12,
    warningA1: amberA.amberA1,
    warningA2: amberA.amberA2,
    warningA3: amberA.amberA3,
    warningA4: amberA.amberA4,
    warningA5: amberA.amberA5,
    warningA6: amberA.amberA6,
    warningA7: amberA.amberA7,
    warningA8: amberA.amberA8,
    warningA9: amberA.amberA9,
    warningA10: amberA.amberA10,
    warningA11: amberA.amberA11,
    warningA12: amberA.amberA12,

    background: '#fff',
  },
  fonts: {
    sans: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
    mono: 'SFMono-Regular, Consolas, "Liberation Mono", Menlo, Courier, monospace',
  },
  fontWeights: {
    regular: 400,
    medium: 500,
    semi: 600,
    bold: 700,
    heavy: 800,
  },
  radii: {
    1: '4px',
    2: '6px',
    3: '8px',
    4: '12px',
    round: '50%',
    pill: '9999px',
  },
  zIndices: {
    1: '100',
    2: '200',
    3: '300',
    4: '400',
    max: '9999',
  },
};
